import { Heading3 } from "@/components/Heading3";
import { LinkBadge, LinkBadgeProps } from "@/components/LinkBadge";
import { Paragraph } from "@/components/Paragraph";
import { TextSpan } from "@/components/TextSpan";
import { useTheme } from "@/hooks/useTheme";
import { AppLayout } from "@/layouts/AppLayouts";
import Head from "next/head";

const quickLinks: LinkBadgeProps[] = [
  {
    href: "mailto:devsamrood@gmail.com",
    label: "Gmail",
  },
  {
    href: "https://www.linkedin.com/in/samrood-ali",
    label: "Linkedin",
  },
  {
    href: "https://github.com/SamroodAli",
    label: "Github",
  },
  {
    href: "https://docs.google.com/document/d/e/2PACX-1vT3xvPGKfzcYs645N2WDpQBFdozD2WQdg5lWbkWSXggqenpHdVnMO68ZQUmyi7Ny7ehgFMB6ftod2h5/pub",
    label: "Resume",
  },
  {
    href: "tel:+917558964767",
    label: "Phone",
  },
];

export default function Home() {
  const { isDarkMode, toggleTheme } = useTheme();

  return (
    <>
      <Head>
        <title>Samrood Ali | Full Stack Web Developer</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <AppLayout className="dark:text-slate-100">
        <header className="my-4 p-3">
          <h1 className="text-2xl md:text-4xl lg:text-5xl font-extrabold">
            Hi! I am Samrood Ali
          </h1>
          <h2 className="font-bold text-day-900 text-xl lg:text-2xl dark:text-teal-300">
            Full Stack web developer{" "}
          </h2>
        </header>

        <section>
          <ul className="flex flex-wrap gap-2 px-2">
            {quickLinks.map((link) => (
              <li key={link.href} className="flex-grow">
                <LinkBadge href={link.href} label={link.label} />
              </li>
            ))}
          </ul>
        </section>

        <section className="p-3" id="intro">
          <Paragraph>Hi there! 👋 Welcome to my personal website.</Paragraph>
          <Paragraph>
            If you are not a fan of the {isDarkMode ? "dark" : "bright"} theme,
            click on the {isDarkMode ? "moon" : "sun"} up top or{" "}
            <span
              className="text-day-900 dark:text-teal-200"
              onClick={toggleTheme}
            >
              here
            </span>{" "}
            to switch to a {isDarkMode ? "lighter" : "darker"} theme.
          </Paragraph>
        </section>

        <section className="p-3">
          <header>
            <Heading3>Who am I ?</Heading3>
          </header>
          <Paragraph>
            I&apos;m a software engineer with a passion for building and
            maintaining innovative web applications. I specialize in Full Stack
            web development. In short, I can handle all your web related needs
          </Paragraph>
        </section>

        <section id="education" className="p-3">
          <header>
            <Heading3>Education</Heading3>
          </header>
          <ul>
            <li className="my-2">
              <Paragraph>
                Despite beginning my career as a
                <TextSpan> Chartered accountancy student</TextSpan> , I made a
                transition to become a software engineer and have since been
                dedicated to the craft.
                <TextSpan> I taught myself to code</TextSpan> with the book
                &apos;Head First Kotlin&apos; and have fallen in love with
                programming ever since.
              </Paragraph>
            </li>
            <li className="my-2">
              <Paragraph>
                To learn front-end web development, I completed
                <TextSpan>
                  {" "}
                  Udacity&apos;s Front-end Nanodegree program
                </TextSpan>
                , which provided me with a strong foundation in web development.
              </Paragraph>
            </li>
            <li className="my-2">
              <Paragraph>
                In addition, I completed a<TextSpan> 1 year</TextSpan>{" "}
                Full-Stack
                <TextSpan> online coding boot-camp, Microverse </TextSpan>,
                which equipped me with the latest programming skills, modern
                development tools, and industry-standard methodologies.
              </Paragraph>
            </li>
            <li>
              <Paragraph>
                I love <TextSpan> Javascript</TextSpan> and have spent countless
                hours honing my JS skills through online resources such as
                <TextSpan> Frontend Masters </TextSpan>
                and
                <TextSpan> You don&apos;t know JS</TextSpan>
              </Paragraph>
            </li>

            <li className="my-3 text-slate-900 dark:text-white rounded-md px-2 italic">
              Sorry, but if you&apos;re searching for a degree, I&apos;m not
              your person. No hard feelings though!
            </li>
          </ul>
        </section>

        <section id="experience" className="p-3">
          <header>
            <Heading3>Experience</Heading3>
            <ul>
              <li>
                <Paragraph>
                  I worked for a year at Superhire, an early stage startup. I
                  was one of the founding full stack web developers there. I
                  wore many hats and worked across the stack. I helped setup
                  repositories and services, and helped build, deploy, test and
                  maintain several features.
                </Paragraph>
              </li>
              <span className="block mt-2 text-sm">
                This section is a work in progress.
              </span>
            </ul>
          </header>
        </section>
      </AppLayout>
    </>
  );
}
